services:
  - type: web
    name: jobtracker
    env: python
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt && python jobtracker/manage.py collectstatic --no-input"
    preDeployCommand: "python jobtracker/manage.py migrate --no-input"
    startCommand: "gunicorn jobtracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobtracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
databases:
  - name: jobtracker-db
    plan: free
