# Generated by Django 5.2.5 on 2025-08-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_contractoruser_options_contractor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="logo_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="contractor_logos/thumbnails/"
            ),
        ),
    ]
