# Generated by Django 5.2.5 on 2025-08-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_contractor_logo_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobentry",
            name="material",
        ),
        migrations.AddField(
            model_name="jobentry",
            name="material_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobentry",
            name="material_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
