# Generated by Django 5.2.5 on 2025-08-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_jobentry_material_jobentry_material_cost_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractor",
            old_name="material_markup",
            new_name="material_margin",
        ),
    ]
