# Generated by Django 5.2.6 on 2025-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_estimateentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_estimate",
            field=models.BooleanField(default=False),
        ),
    ]
