# Generated by Django 5.2.6 on 2025-09-04 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_project_is_estimate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimateentry",
            name="project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_estimate",
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="tracker.contractor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estimateentry",
            name="estimate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="tracker.estimate",
            ),
            preserve_default=False,
        ),
    ]
