# Generated by Django 5.2.6 on 2025-09-04 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def forward_migrate_estimates(apps, schema_editor):
    """Move legacy estimate projects to dedicated Estimate rows."""

    Estimate = apps.get_model("tracker", "Estimate")
    EstimateEntry = apps.get_model("tracker", "EstimateEntry")
    Project = apps.get_model("tracker", "Project")

    # Create Estimate records for any projects flagged as estimates and
    # point their estimate entries at the new rows.
    for project in Project.objects.filter(is_estimate=True).iterator():
        estimate = Estimate.objects.create(
            contractor=project.contractor,
            name=project.name,
            created_date=getattr(project, "start_date", None)
            or django.utils.timezone.now().date(),
        )
        EstimateEntry.objects.filter(project=project).update(estimate=estimate)

    # Remove any estimate entries that still lack an estimate after the
    # migration to prevent NOT NULL constraint failures.
    EstimateEntry.objects.filter(estimate__isnull=True).delete()


def reverse_migrate_estimates(apps, schema_editor):
    pass


class CreateModelIfNotExists(migrations.CreateModel):
    def __init__(self, *args, **kwargs):
        kwargs.pop("if_not_exists", None)
        super().__init__(*args, **kwargs)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table in schema_editor.connection.introspection.table_names():
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        if model._meta.db_table not in schema_editor.connection.introspection.table_names():
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("tracker", "0007_project_is_estimate"),
    ]

    operations = [
        CreateModelIfNotExists(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "created_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="tracker.contractor",
                    ),
                ),
            ],
            if_not_exists=True,
        ),
        migrations.AddField(
            model_name="estimateentry",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="tracker.estimate",
            ),
        ),
        migrations.RunPython(forward_migrate_estimates, reverse_migrate_estimates),
        migrations.RemoveField(
            model_name="estimateentry",
            name="project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_estimate",
        ),
        migrations.AlterField(
            model_name="estimateentry",
            name="estimate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="tracker.estimate",
            ),
        ),
    ]


