# Generated by Django 5.2.6 on 2025-09-05 02:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_remove_estimateentry_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimateentry",
            name="service_markup",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Percentage markup for outside services",
                max_digits=5,
            ),
        ),
    ]
