# Generated by Django 5.2.8 on 2025-12-02 01:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_estimateentry_service_markup"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="customer_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="estimate",
            name="customer_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="estimate",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="estimate",
            name="estimate_number",
            field=models.CharField(
                blank=True,
                help_text="Estimate number for customer reference",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="exclusions",
            field=models.TextField(
                blank=True, help_text="Work or materials not included in this estimate"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="liability_statement",
            field=models.TextField(
                blank=True,
                default="Contractor maintains general liability insurance. Customer responsible for permits unless otherwise specified.",
                help_text="Liability and insurance information",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes (not shown to customer)"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="payment_terms",
            field=models.TextField(
                blank=True,
                default="50% deposit required upon acceptance. Balance due upon completion.",
                help_text="Payment terms and conditions",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="project_description",
            field=models.TextField(
                blank=True, help_text="Brief description of the work"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="project_location",
            field=models.TextField(blank=True, help_text="Job site address"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="special_terms",
            field=models.TextField(
                blank=True, help_text="Additional terms, warranties, or conditions"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Customer"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="valid_until",
            field=models.DateField(
                blank=True, help_text="Estimate expiration date", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobentry",
            name="service_markup",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Percentage markup for outside services",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                help_text="Source estimate for this project, if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="tracker.estimate",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="name",
            field=models.CharField(
                help_text="Internal name for this estimate", max_length=255
            ),
        ),
    ]
